USE corvinsadventure;

INSERT INTO LEVEL (LEVELID,LEVELNAME) VALUES (1,'The Day it all began');

INSERT INTO LEVEL (LEVELID,LEVELNAME) VALUES (2,'High flies the Vulture');

INSERT INTO DICE (DICECOLOR,SIDE1,SIDE2,SIDE3,SIDE4,SIDE5,SIDE6) VALUES ('green','ATK * 1.5','DEF * 1.5',NULL,NULL,'DEF * 0.5','ATK * 0.5');

INSERT INTO DICE (DICECOLOR,SIDE1,SIDE2,SIDE3,SIDE4,SIDE5,SIDE6) VALUES ('yellow','ATK * 1.5 + SPE * 2',NULL,NULL,NULL,NULL,'ATK * 0.5 + DEF * 0.5');

INSERT INTO ENEMY (ENEMYID,ENEMYNAME,ENEMYLP,ENEMYMAN,ENEMYATK,ENEMYDEF,ENEMYSPE,ENEMYLVL,ENEMYSKILL,LEVELID,DICECOLOR) VALUES (1,'Burglar', 4,NULL,3,1,3,1,NULL,1,'green');

INSERT INTO ENEMY (ENEMYID,ENEMYNAME,ENEMYLP,ENEMYMAN,ENEMYATK,ENEMYDEF,ENEMYSPE,ENEMYLVL,ENEMYSKILL,LEVELID,DICECOLOR) VALUES (2,'Criminal', 7,NULL,4,2,6,1,NULL,2,'yellow');

INSERT INTO ENEMY (ENEMYID,ENEMYNAME,ENEMYLP,ENEMYMAN,ENEMYATK,ENEMYDEF,ENEMYSPE,ENEMYLVL,ENEMYSKILL,LEVELID,DICECOLOR) VALUES (3,'Vulture',NULL,NULL,NULL,NULL,NULL,NULL,NULL,2,NULL);

COMMIT WORK;